### ISSUE TITLE
DateTime.now persistently throws argument error

### ISSUE THREAD

**Issue by deadeyejoe** [rubysl/rubysl-date#13]
My application runs fine for a while. At a certain point all calls to DateTime.now start throwing an argument error. From my observations so far this occurs a random amount of time (several hours) after the application starts, and the error persists indefinitely. Stack trace is:

```
home/apps/.rvm/rubies/rbx-3.21/gems/gems/rubysl-date-2.0.9/lib/rubysl/date/date.rb:812:in `new! (civil)'
home/apps/.rvm/gems/rbx-3.21@global/gems/rubysl-date-2.0.9/lib/rubysl/date/date.rb:1828:in `now'
```

My application consists of a puma rails app and a sidekiq process, the error starts to appear simultaneously in both processes. 
- Restarting the puma process on its own does not fix the problem. (I'm doing a hard restart)
- Restarting the sidekiq process fixes the problem in that process, but not the puma process. 
- Stopping both processes and restarting them fixes the error in both.
- If I start a rails console while the errors are happening in the application processes, the error does not occur in the console.

I am using rbx-3.21 on ubuntu 14.04. Please let me know if you need any further information.

**Comment by brixen** [comment]
@deadeyejoe would it be possible to gist a backtrace from the ArgumentError? Also, could you paste `rbx -v`?

**Comment by brixen** [comment]
@deadeyejoe sorry, I meant a full backtrace. It's printing more than those two lines, isn't it?

**Comment by deadeyejoe** [comment]
The full stack trace is [here](https://gist.github.com/deadeyejoe/e67882d57bcd9539fea474155a9821e8)

The output of rbx -v is:
```
rubinius 3.21 (2.2.2 089e9eba 2016-03-29 3.5.0) [x86_64-linux-gnu]
```
Thanks!

**Comment by brixen** [comment]
@deadeyejoe wow, the description you have is _super_ puzzling. I've been fixing concurrency related issues throughout the 3.x line and recently removed the copying young generation GC and JIT to rewrite them. I'm at a loss to explain nondeterministic behavior without components like that running.

A couple things to consider:

1. Try running on 3.30, the most recent release.
2. Investigate whether anything is loading code that may be changing that method. One thing you could do is put a rescue in your code and print out the method object for `new!`. I'll show a gist of how you might do that below.
3. Try to extract a repro from your application or give me access to a private repo so I can attempt to repro this.

To show where the method is defined, you can do something like the following:

```ruby
$ irb
irb(main):001:0> RUBY_DESCRIPTION
=> "rubinius 3.30 (2.2.2 282c0312 2016-05-06 3.6.2) [x86_64-darwin13.4.0]"
irb(main):002:0> require "date"
=> true
irb(main):003:0> DateTime.method(:new!)
=> #<Method: Class#new! (defined in Class at core/alpha.rb:90)>
```

Another thing you may want to try if you instrument the code with a rescue is printing out the inline caches for the method that is calling whatever method is raising an ArgumentError. The snippet below follows from the one above and should give you enough to modify this for your needs. If not, I'll help you with the code you need:

```ruby
irb(main):004:0> _.executable
=> #<Rubinius::CompiledCode:0x1aa8 new file=core/alpha.rb>
irb(main):005:0> _.call_sites
=> #<Rubinius::Tuple: #<Rubinius::CallSite:0x1c18 name=allocate ip=2 depth=3 invokes=497 hits=1170 misses=1005>, #<Rubinius::CallSite:0x1c1c name=initialize ip=13 depth=3 invokes=496 hits=1170 misses=1004>>
```

You certainly have an unusual case here. Let me know how I can help you continue debugging it.

**Comment by deadeyejoe** [comment]
@brixen Thanks so much for the advice. I'm going to try switching to 3.30 and instrumenting the code like you suggested. 

As is typical for things like this, the moment I made a post about it, it stopped happening! I'll keep an eye on it and come back to you when I have more info.

Thanks again.

**Comment by deadeyejoe** [comment]
@brixen Just observed the error again. I've updated the [gist](https://gist.github.com/deadeyejoe/e67882d57bcd9539fea474155a9821e8) with the information you were looking for. I haven't upgraded to 3.30 yet so I'm going to do that now and see what happens. Thanks

**Comment by brixen** [comment]
@deadeyejoe ah, interesting! Thanks for instrumenting it and getting more info.

The version you are running still has the old inline cache mechanism. I've replaced them and I'd be super curious to see if you're still hitting the issue on 3.30.

**Comment by deadeyejoe** [comment]
Hi @brixen,

I updated the rbx version to 3.30 and after a long absence I'm afraid that the issue has reared it's ugly head again. I've updated the gist with the stack trace and instrumentation from the new version. Any thoughts?

**Comment by brixen** [comment]
@deadeyejoe 3.42 is the current release and I'm at this moment reworking the inline cache a bit more and planning to tag 3.43 today. You should try with 3.43. Ultimately, I need to have a repro to work with or access to running your code.
